name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora

    steps:
      - uses: actions/checkout@v3
      - name: prereqs_1
        run: docker pull slothai/openblas
      - name: prereqs_2
        run: docker pull kitware/cmake
      - name: configure
        run: cmake ./
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
